spring.application.name=EM_Project

#Database setup
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

#Database Connector
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#if table does not exist then update here directly
spring.jpa.hibernate.ddl-auto=update
